---
title: "Vignette Title"
author: "Vignette Author"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
library(cityDensities)
library(tidyverse)
library(gganimate)
```


## Hong Kong
```{r}
get_city_locations() %>% filter(name=="Hong Kong") %>% top_n(1,pop) %>%
  plot_facet(.,radius_km=30,ncol=1,
             bks=c(1,4,50.00, 100.00,250,500,750,1000,1500),smoothing=250) %>%
  ggplot2::ggsave("~/Desktop/density_series0.png",.,width=12,height=8.5)
```

## Dubai
```{r}
get_city_locations() %>% filter(name=="Dubai") %>% top_n(1,pop) %>%
  plot_density_facet(.,radius_km=50) %>%
  ggplot2::ggsave("~/Desktop/density_series9.png",.,width=12,height=8.5)
```

## Abu Dhabi
```{r}
get_city_locations() %>% filter(name=="Abu Dhabi") %>% top_n(1,pop) %>%
  plot_density_facet(.,radius_km=40) %>%
  ggplot2::ggsave("~/Desktop/density_series10.png",.,width=12,height=8.5)
```

## Riyadh
```{r}
get_city_locations() %>% filter(name=="Riyadh") %>% top_n(1,pop) %>%
  plot_density_facet(.,radius_km=50) %>%
  ggplot2::ggsave("~/Desktop/density_series10.png",.,width=12,height=8.5)
```

## Jeddah
```{r}
get_city_locations() %>% filter(name=="Jeddah") %>% top_n(1,pop) %>%
  plot_density_facet(.,radius_km=50) %>%
  ggplot2::ggsave("~/Desktop/density_series10.png",.,width=12,height=8.5)
```

## Kuwait City
```{r}
get_city_locations() %>% filter(name=="al-Kuwayt") %>% mutate(name="Kuwait") %>% top_n(1,pop) %>%
  plot_density_facet(.,radius_km=50) %>%
  ggplot2::ggsave("~/Desktop/density_series10.png",.,width=12,height=8.5)
```

## Mecca
```{r}
get_city_locations() %>% filter(name=="Mecca") %>% top_n(1,pop) %>%
  plot_density_facet(.,radius_km=25) %>%
  ggplot2::ggsave("~/Desktop/density_series10.png",.,width=12,height=8.5)
```



## St Louis
```{r}
get_city_locations() %>% filter(name=="Saint Louis") %>% top_n(1,pop) %>%
  plot_density_facet(.,radius_km=40) %>%
  ggplot2::ggsave("~/Desktop/density_series10.png",.,width=12,height=8.5)
```

## San Diego
```{r}
get_city_locations() %>% filter(name=="San Diego") %>% top_n(1,pop) %>%
  plot_density_facet(.,radius_km=30) %>%
  ggplot2::ggsave("~/Desktop/density_series11.png",.,width=12,height=8.5)
```

## Manila
```{r}
get_city_locations() %>% filter(name=="Manila") %>% top_n(1,pop) %>%
  plot_density_facet(.,radius_km=50) %>%
  ggplot2::ggsave("~/Desktop/density_series13.png",.,width=12,height=8.5)
```

## El Paso
```{r}
get_city_locations() %>% filter(name=="El Paso") %>% top_n(1,pop) %>%
  plot_density_facet(.,radius_km=30) %>%
  ggplot2::ggsave("~/Desktop/density_series12.png",.,width=12,height=8.5)
```

## Lagos
```{r}
get_city_locations() %>% filter(name=="Lagos") %>% top_n(1,pop) %>%
  plot_density_facet(.,radius_km=50) %>%
  ggplot2::ggsave("~/Desktop/density_series_lagos.png",.,width=12,height=8.5)
```

 ## La Plata
```{r}
get_city_locations() %>% filter(name=="La Plata") %>% top_n(1,pop) %>%
  plot_density_facet(.,radius_km=20) %>%
  ggplot2::ggsave("~/Desktop/density_series_la_plata.png",.,width=12,height=8.5)
```

## Cleveland
```{r}
get_city_locations() %>% filter(name=="Cleveland") %>% top_n(1,pop) %>%
  plot_density_facet(.,radius_km=35) %>%
  ggplot2::ggsave("~/Desktop/density_series13.png",.,width=12,height=8.5)
```

## Seoul
```{r}
get_city_locations() %>% filter(name=="Seoul") %>% top_n(1,pop) %>%
  plot_density_facet(.,radius_km=35) %>%
  ggplot2::ggsave("~/Desktop/density_series14.png",.,width=12,height=8.5)
```


```{r}
cities <-c("Barcelona","Madrid","Valencia","Athens","Paris","Sevilla","Vienna","Sofia","Naples","Turin","Lyon","Brussels","Rome",
  "Warsaw","Amsterdam","Berlin","London","Lisbon","Prague","Budapest","Munich","Rotterdam","Copenhagen","Milan",
  "Katowice","Stockholm","Hamburg","Cologne","Dusseldorf","Toronto","Montreal","Frankfurt","Wellington","Dublin","Vancouver",
  "Liverpool","Birmingham","Porto","Manchester","Stuttgart","Helsinki","Glasgow","Sydney","Ottawa","Calgary","Auckland","Edmonton",
  "Melbourne","Christchurch","Adelaide","Brisbane","Perth")

locations <- get_city_locations() %>%
  filter(name %in% cities,country.etc!="Venezuela") %>% 
  group_by(name) %>% 
  top_n(1,pop) %>%
  ungroup %>%
  left_join(tibble(name=cities,n=seq(1,length(cities)))) %>%
  arrange(n)



data <- get_population_weighted_data(locations)


featured_countries <- c(
  "Spain",
  "France",
  "Italy",
  "Germany",
  "UK",
  "Australia",
  "Canada",
  "New Zealand")

plot_data <- data %>% 
  mutate(label=ifelse(country.etc %in% featured_countries,as.character(country.etc),"Other")) %>%
  mutate(label=factor(label,levels=c(featured_countries,"Other")))

ggplot(plot_data,aes(x=reorder(name,density),y=density,fill=label)) +
  geom_bar(stat="identity") +
  coord_flip() +
  geom_text(aes(label=round(density),y=density/2,hjust=0)) +
  scale_fill_brewer(palette = "Set1") +
  labs(title="2015 population weighted densities, 30km radius, 250m grid",x="",y="People/ha",
       fill="",caption=ghs_attribution_linebreak)
```


```{r}
asian_cities <-c("Tokyo","Osaka","Nagoya","Taipei","Kaohsiung","Jakarta","Surabaya","Manila","Ha Noi",
                 "Ho Chi Minh City","Beijing","Shanghai","Chongqing","Hong Kong","Singapore",
                 "Delhi","Bangalore","Dhaka","Mumbai","Calcutta","Karachi","Lahore","Seoul","Pusan","Pyongyang","Bangkok")

locations <- get_city_locations() %>% filter(name %in% asian_cities,country.etc!="Venezuela") %>% group_by(name) %>% top_n(1,pop)

data <- get_population_weighted_data(locations,years=c("1975","1990","2000","2015"))

featured_countries <- c(
  "Vietnam",
  "China",
  "Taiwan",
  "Japan",
  "India",
  "Pakistan",
  "Korea South")

plot_data <- data %>%
  mutate(label=ifelse(country.etc %in% featured_countries,as.character(country.etc),"Other")) %>%
  mutate(label=factor(label,levels=c(featured_countries,"Other"))) %>%
  mutate(Year=as.integer(as.character(Year))) %>%
  group_by(Year) %>%
  mutate(rank = min_rank(density)*1) %>%
  ungroup() %>%
  mutate(colour=set_names(RColorBrewer::brewer.pal(length(featured_countries)+1,"Set1"),c(featured_countries,"Other"))[as.character(label)])

colours <- plot_data %>% 
  st_set_geometry(NULL) %>%
  select(name,country.etc,label,colour) %>% 
  unique %>%
  mutate(name=as.character(name),country.etc=as.character(country.etc),label=as.character(label))

p<-ggplot(plot_data,aes(x=rank,y=density,fill=name,label=name)) +
  geom_bar(stat="identity") +
  coord_flip(clip = "off", expand = FALSE) +
  geom_text(aes(y = 0), hjust = 1,nudge_y = -50) +
  scale_fill_manual(values=set_names(colours$colour,colours$name),guide=FALSE)+
  theme_light() +
  geom_point(shape=NA,aes(color=label)) +
  scale_colour_manual(values=set_names(colours$colour,colours$label))+
  guides(color=guide_legend("", override.aes=list(shape=15, size = 10))) +
  theme(axis.ticks.y = element_blank(),
        axis.text.y  = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank(),
        panel.border = element_blank(),
        plot.margin=unit(c(5.5, 5.5, 5.5, 85.5), "points")) + 
  labs(title="{frame_time} population weighted densities, 30km radius, 250m grid",x="",y="People/ha",
       fill="",caption=ghs_attribution_linebreak,subtitle="(Interpolated based on 1975, 1990, 2000 and 2015 estimates)") +
  transition_time(Year) +
  ease_aes('linear')

pp<-animate(p, end_pause = 20,start_pause=20) 
#anim_save("~/Desktop/population_weighted_densities.gif",pp)
```




```{r}
data <- get_population_weighted_data(locations,years=c("1975","1990","2000","2015"),type="1k")

plot_data <-   data %>%
  mutate(label=ifelse(country.etc %in% featured_countries,as.character(country.etc),"Other")) %>%
  mutate(label=factor(label,levels=c(featured_countries,"Other"))) %>%
  mutate(colour=set_names(RColorBrewer::brewer.pal(length(featured_countries)+1,"Set1"),c(featured_countries,"Other"))[as.character(label)]) %>%
  rename(Value=density) %>%
  mutate(Year=as.integer(as.character(Year)))



gganimate::animate(bar_race_animation(plot_data), end_pause = 20,start_pause=20,height=800,width=700) 
```



```{r fig.height=10}
data <- get_population_weighted_data(locations,years=c("1975","1990","2000","2015"),type="1k")

plot_data <- data %>%
  mutate(label=ifelse(country.etc %in% featured_countries,as.character(country.etc),"Other")) %>%
  mutate(label=factor(label,levels=c(featured_countries,"Other"))) %>%
  mutate(Year=as.integer(as.character(Year))) %>%
  group_by(Year) %>%
  mutate(rank = min_rank(density)*1) %>%
  ungroup() %>%
  mutate(colour=set_names(RColorBrewer::brewer.pal(length(featured_countries)+1,"Set1"),c(featured_countries,"Other"))[as.character(label)])

colours <- plot_data %>% 
  dplyr::select(name,country.etc,label,colour) %>% 
  unique %>%
  mutate(name=as.character(name),country.etc=as.character(country.etc),labels=as.character(label))

p<-ggplot(plot_data,aes(x=rank,y=density,fill=name,label=name)) +
  geom_bar(stat="identity") +
  coord_flip(clip = "off", expand = FALSE) +
  geom_text(aes(y = 0), hjust = 1,nudge_y = -50) +
  scale_fill_manual(values=set_names(colours$colour,colours$name),guide=FALSE)+
  theme_light() +
  geom_point(shape=NA,aes(color=label)) +
  scale_colour_manual(values=set_names(colours$colour,colours$label))+
  guides(color=guide_legend("", override.aes=list(shape=15, size = 10))) +
  theme(axis.ticks.y = element_blank(),
        axis.text.y  = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank(),
        panel.border = element_blank(),
        plot.margin=unit(c(5.5, 5.5, 5.5, 85.5), "points")) + 
  labs(title="{frame_time} population weighted densities, 30km radius, 1km grid",x="",y="People/ha",
       fill="",caption=caption,subtitle="(Interpolated based on 1975, 1990, 2000 and 2015 estimates)") +
  transition_time(Year) +
  ease_aes('linear')

pp<-gganimate::animate(p, end_pause = 20,start_pause=20,height=800,width=700) 
gganimate::anim_save("~/Desktop/density_race_1k.gif",pp)
```



```{r}

cities <- c("Seattle","Toronto","Vancouver","San Francisco","New York",
            "Chicago","Atlanta","London","Paris","Vienna","Athens","Barcelona","Taipei","Hong Kong","Singapore")
locations <- get_city_locations() %>% filter(name %in% cities) %>% group_by(name) %>% top_n(1,pop)

data <- get_population_weighted_data(locations,years=c("1975","1990","2000","2015"),max_radius_km = 25,type="1k")

plot_data <-   data %>%
  mutate(label=case_when(name %in% c("New York","Chicago","Atlanta","Seattle","Toronto","Vancouver","San Francisco") ~ "North America",
                         name %in% c("London","Paris","Vienna","Athens","Barcelona") ~ "Europe",
                         name %in% c("Taipei","Hong Kong","Singapore") ~ "Asia",
                         TRUE ~ "Other")) %>%
  mutate(label=factor(label)) %>%
  mutate(colour=set_names(RColorBrewer::brewer.pal(length((.)$label %>% unique),"Set1"),(.)$label %>% unique)[as.character(label)]) %>%
  rename(Value=density) %>%
  mutate(Year=as.integer(as.character(Year)))

plot <- bar_race_animation(plot_data) +
  labs(title="{frame_time} population weighted densities, 25km radius, 1km grid",caption=ghs_attribution_linebreak)

gganimate::animate(plot, end_pause = 20,start_pause=20,height=800,width=700) 
```
